// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfsjlbllqdpuxrawitpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmc2psYmxscWRwdXhyYXdpdHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mzg0NzEsImV4cCI6MjA2NjAxNDQ3MX0.NNK2Hrjt9-UXBOC8SGuKfxODTDlVJcgZuvOTl6CGRmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});